//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicMattersMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flaggable
    {
        public int Id { get; set; }
        public int FlagId { get; set; }
        public string FlaggableType { get; set; }
        public int FlaggableId { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual Flag Flag { get; set; }
    }
}
