//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicMattersMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public int Id { get; set; }
        public Nullable<int> AlbumId { get; set; }
        public string Name { get; set; }
        public Nullable<System.TimeSpan> Length { get; set; }
        public Nullable<byte> IsSingle { get; set; }
        public byte IsAdminApproved { get; set; }
    
        public virtual Album Album { get; set; }
    }
}
